---
name: Upload S3 object and Lambda code

# Controls when the action will run. Invokes the workflow on push events but only for the main branch
on:
  push:
    branches: [ main ]

env:
  AWS_REGION : "us-east-2"

# Permission can be added at job level or workflow level    
permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout

jobs:
  UploadFunctionCodeAndUpdate:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      
      - name: UploadFunctionCodeAndUpdate
        run: |
          cd function && zip lambda_function.zip lambda_function.py
          aws s3 cp lambda_function.zip s3://${{ secrets.S3_BUCKET }}/
          aws lambda update-function-code --function-name ${{ vars.FUNCTION_NAME }} --s3-bucket ${{ secrets.S3_BUCKET }} --s3-key lambda_function.zip
